### ISSUE TITLE
Rotate molecules in a customized region

### ISSUE THREAD

**Issue by qzhu2017** [MaterSim/pyocse#1]
```python 
   def rotate_molecules(self, ase_struc, mol_list, region, rotation):
        """
        selectively rotate some molecules based on boundary conditions.

        Args:
            ase_struc: ase atoms
            region:
            rotation:
        """
        centers = self.get_molecular_centers(ase_struc, mol_list)
        for id, center in enumerate(centers):
            if in_region(center, region):
                # rotate this molecule
                mol_xyz = 
                
        for ase_struc_rotated
```

**Comment by qzhu2017** [comment]
<img width="709" alt="image" src="https://github.com/MaterSim/OST/assets/29445366/364badce-792a-4823-a77d-dd5ca9b6acf1">

<img width="788" alt="image" src="https://github.com/MaterSim/OST/assets/29445366/79cb2249-4bb3-43d5-9274-17dedc7fa6b3">

<img width="765" alt="image" src="https://github.com/MaterSim/OST/assets/29445366/b488b33f-183b-49e6-9d2c-5d9947e8f515">

**Comment by qzhu2017** [comment]
@pedroantoniosantosf 

How can I add an additional column of potential energy in the following file
```
fix def1 all print ${thermo} "${step} ${p1} ${p2} ${p3} ${p4}" file tensile.dat screen no
fix def2 all ave/time 2 100 ${thermo} v_p1 v_p2 v_p3 v_p4 file tensile_mean.dat
```

https://github.com/MaterSim/OST/blob/cbe17d579f3773030973ac0e0fe8cc4ff33b0241/ost/templates/tensile.in#L65C1-L66C1

**Comment by pedroantoniosantosf** [comment]
@qzhu2017 

In order to add an additional column of potential energy, you can create a variable and call similar to the variable "step":

```
variable pe equal pe
fix def1 all print ${thermo} "${step} ${p1} ${p2} ${p3} ${p4} ${pe}" file tensile.dat screen no
fix def2 all ave/time 2 100 ${thermo} v_p1 v_p2 v_p3 v_p4 v_pe file tensile_mean.dat
```
